server:
  port: 8081

microservices:
  url:
    base:
      person: ${MICROSERVICES_URL_BASE_PERSON:http://localhost:8080}
    get:
      genres: ${MICROSERVICES_URL_GET_GENRES:/people/genres}

spring:
  flyway:
    baseline-on-migrate: true
    enabled: true
  datasource:
    url: ${SPRING_DATASOURSE_URL:jdbc:postgresql://localhost:5432/red_collar}
    username: ${SPRING_DATASOURSE_USERNAME:shadow-fiend}
    password: ${SPRING_DATASOURSE_PASSWORD:qqqqqq}
    driverClassName: org.postgresql.Driver
    hikari:
      schema: ${SPRING_DATASOURSE_HIKARI_SCHEMA:platform}

management:
  endpoint:
    flyway:
      enabled: true
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: health, flyway