server:
  port: 8081

microservices:
  url:
    test: http://localhost:8080

spring:
  flyway:
    baseline-on-migrate: true
    enabled: true
  datasource:
    url: jdbc:postgresql://localhost:5432/test
    username: shadow-fiend
    password: qqqqqq
    driverClassName: org.postgresql.Driver
    hikari:
      schema: platform